# Generated by Django 4.2.5 on 2023-12-03 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='recipe id')),
                ('instructions', models.CharField(max_length=5000, verbose_name='instructions')),
                ('recipe_name', models.CharField(max_length=100, verbose_name='recipe name')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.company', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'recipe',
                'verbose_name_plural': 'recipes',
                'ordering': ['-recipe_name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('tracking_number', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='tracking number')),
                ('description', models.CharField(max_length=500, verbose_name='shipment description')),
                ('ordered', models.DateTimeField(verbose_name='order date')),
                ('expected', models.DateTimeField(verbose_name='expected arrival')),
                ('delivered', models.DateTimeField(verbose_name='recorded delivery')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.company', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'shipment',
                'verbose_name_plural': 'shipments',
                'ordering': ['-ordered'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('supply_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='supply id')),
                ('storage_location', models.CharField(max_length=20, verbose_name='storage location')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('quantity_units', models.CharField(max_length=20, verbose_name='units')),
                ('resupply', models.BooleanField(verbose_name='in stock')),
                ('supply_name', models.CharField(max_length=5000, verbose_name='supply name')),
                ('supply_type', models.CharField(choices=[('INGREDIENT', 'used as an ingredient'), ('MATERIAL', 'not used as an ingredient')], max_length=20, verbose_name='supply type')),
                ('supply_description', models.CharField(default='', max_length=5000, verbose_name='supply description')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.company', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'supply',
                'verbose_name_plural': 'supplies',
                'ordering': ['-supply_name'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.shipment', verbose_name='shipment number')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.supply', verbose_name='supply id')),
            ],
            options={
                'verbose_name': 'active shipment supply association',
                'verbose_name_plural': 'active shipment supply associations',
            },
        ),
        migrations.CreateModel(
            name='RestockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_quantity', models.PositiveIntegerField()),
                ('date_restocked', models.DateTimeField(auto_now_add=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.supply')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.recipe', verbose_name='recipe id')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.supply', verbose_name='supply id')),
            ],
            options={
                'verbose_name': 'recipe supply association',
                'verbose_name_plural': 'recipe supply associations',
            },
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['supply_name'], name='stock_suppl_supply__cbe8af_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentsupply',
            constraint=models.UniqueConstraint(fields=('shipment', 'supply'), name='unique_shipment_supply'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['ordered'], name='stock_shipm_ordered_169b30_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipesupply',
            constraint=models.UniqueConstraint(fields=('recipe', 'supply'), name='unique_recipe_supply'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['recipe_name'], name='stock_recip_recipe__cc1820_idx'),
        ),
    ]
