# Generated by Django 4.2.5 on 2023-12-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_recipe_shipment_supply_shipmentsupply_recipesupply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='supply_description',
            field=models.CharField(default='placeholder description', max_length=5000, verbose_name='supply description'),
            preserve_default=False,
        ),
    ]
