# Generated by Django 4.2.5 on 2023-10-17 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='company id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('username', models.CharField(max_length=70, primary_key=True, serialize=False, verbose_name='username')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('email', models.CharField(max_length=320, verbose_name='email')),
                ('user_password', models.CharField(max_length=50, verbose_name='password')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.company', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'worker',
                'verbose_name_plural': 'workers',
            },
        ),
    ]
