# Generated by Django 4.2.6 on 2023-10-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("recipe_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("instructions", models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "restaurant_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurants",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "tracking_number",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("ordered", models.DateTimeField()),
                ("expected", models.DateTimeField()),
                ("delivered", models.DateTimeField()),
                (
                    "restaurant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "username",
                    models.CharField(max_length=70, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=320)),
                ("user_password", models.CharField(max_length=50)),
                (
                    "restaurant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                ("supply_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("storage_location", models.CharField(max_length=20)),
                ("quantity", models.IntegerField()),
                ("resupply", models.BooleanField()),
                (
                    "restaurant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShipmentSupply",
            fields=[
                (
                    "shipment_supply_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("amount", models.IntegerField()),
                (
                    "shipment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.shipment",
                    ),
                ),
                (
                    "supply_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.supply",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="restaurant",
            name="restaurants_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="database.restaurants"
            ),
        ),
        migrations.CreateModel(
            name="RecipeSupply",
            fields=[
                (
                    "recipe_supply_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("amount", models.FloatField()),
                (
                    "recipe_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.recipe",
                    ),
                ),
                (
                    "supply_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.supply",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="restaurant_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="database.restaurant"
            ),
        ),
    ]
