# Generated by Django 4.2.6 on 2023-10-05 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="restaurant_id",
            new_name="restaurant",
        ),
        migrations.RenameField(
            model_name="recipesupply",
            old_name="recipe_id",
            new_name="recipe",
        ),
        migrations.RenameField(
            model_name="recipesupply",
            old_name="supply_id",
            new_name="supply",
        ),
        migrations.RenameField(
            model_name="restaurant",
            old_name="restaurants_id",
            new_name="restaurants",
        ),
        migrations.RenameField(
            model_name="shipment",
            old_name="restaurant_id",
            new_name="restaurant",
        ),
        migrations.RenameField(
            model_name="shipmentsupply",
            old_name="shipment_id",
            new_name="shipment",
        ),
        migrations.RenameField(
            model_name="shipmentsupply",
            old_name="supply_id",
            new_name="supply",
        ),
        migrations.RenameField(
            model_name="supply",
            old_name="restaurant_id",
            new_name="restaurant",
        ),
        migrations.RenameField(
            model_name="worker",
            old_name="restaurant_id",
            new_name="restaurant",
        ),
    ]
