# Generated by Django 4.2.6 on 2023-10-05 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0002_rename_restaurant_id_recipe_restaurant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipesupply",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="recipesupply",
            name="supply",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="restaurants",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="restaurant",
        ),
        migrations.RemoveField(
            model_name="shipmentsupply",
            name="shipment",
        ),
        migrations.RemoveField(
            model_name="shipmentsupply",
            name="supply",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="restaurant",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="restaurant",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
        migrations.DeleteModel(
            name="RecipeSupply",
        ),
        migrations.DeleteModel(
            name="Restaurant",
        ),
        migrations.DeleteModel(
            name="Restaurants",
        ),
        migrations.DeleteModel(
            name="Shipment",
        ),
        migrations.DeleteModel(
            name="ShipmentSupply",
        ),
        migrations.DeleteModel(
            name="Supply",
        ),
        migrations.DeleteModel(
            name="Worker",
        ),
    ]
