# Generated by Django 4.2.5 on 2023-10-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesupply',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipesupply',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurants',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='shipmentsupply',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='shipmentsupply',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeSupply',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Restaurants',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='ShipmentSupply',
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
